package com.meals.backend.model;
// Generated Mar 20, 2018 2:44:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CateringId generated by hbm2java
 */
@Embeddable
public class CateringId  implements java.io.Serializable {


     private String staffId;
     private int mealTimeId;
     private Date cateringDate;

    public CateringId() {
    }

    public CateringId(String staffId, int mealTimeId, Date cateringDate) {
       this.staffId = staffId;
       this.mealTimeId = mealTimeId;
       this.cateringDate = cateringDate;
    }
   


    @Column(name="StaffId", nullable=false, length=12)
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }


    @Column(name="MealTimeId", nullable=false)
    public int getMealTimeId() {
        return this.mealTimeId;
    }
    
    public void setMealTimeId(int mealTimeId) {
        this.mealTimeId = mealTimeId;
    }


    @Column(name="CateringDate", nullable=false, length=10)
    public Date getCateringDate() {
        return this.cateringDate;
    }
    
    public void setCateringDate(Date cateringDate) {
        this.cateringDate = cateringDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CateringId) ) return false;
		 CateringId castOther = ( CateringId ) other; 
         
		 return ( (this.getStaffId()==castOther.getStaffId()) || ( this.getStaffId()!=null && castOther.getStaffId()!=null && this.getStaffId().equals(castOther.getStaffId()) ) )
 && (this.getMealTimeId()==castOther.getMealTimeId())
 && ( (this.getCateringDate()==castOther.getCateringDate()) || ( this.getCateringDate()!=null && castOther.getCateringDate()!=null && this.getCateringDate().equals(castOther.getCateringDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getStaffId() == null ? 0 : this.getStaffId().hashCode() );
         result = 37 * result + this.getMealTimeId();
         result = 37 * result + ( getCateringDate() == null ? 0 : this.getCateringDate().hashCode() );
         return result;
   }   


}


