package com.meals.backend.model;
// Generated Mar 20, 2018 2:44:46 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name="Staff"
    ,schema="dbo"
    ,catalog="nsrp"
)
public class Staff  implements java.io.Serializable {


     private String staffId;
     private String staffName;
     private String jobTitle;
     private String address;
     private String phoneNum;
     private String email;
     private int deptId;
     private String gender;
     private String cardId;
     private boolean disable;
     private Integer age;
     private String position;
     private String provice;
     private String nationality;

    public Staff() {
    }

	
    public Staff(String staffId, String staffName, int deptId, boolean disable) {
        this.staffId = staffId;
        this.staffName = staffName;
        this.deptId = deptId;
        this.disable = disable;
    }
    public Staff(String staffId, String staffName, String jobTitle, String address, String phoneNum, String email, int deptId, String gender, String cardId, boolean disable, Integer age, String position, String provice, String nationality) {
       this.staffId = staffId;
       this.staffName = staffName;
       this.jobTitle = jobTitle;
       this.address = address;
       this.phoneNum = phoneNum;
       this.email = email;
       this.deptId = deptId;
       this.gender = gender;
       this.cardId = cardId;
       this.disable = disable;
       this.age = age;
       this.position = position;
       this.provice = provice;
       this.nationality = nationality;
    }
   
     @Id 

    
    @Column(name="StaffId", unique=true, nullable=false, length=12)
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }

    
    @Column(name="StaffName", nullable=false, length=50)
    public String getStaffName() {
        return this.staffName;
    }
    
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    
    @Column(name="JobTitle", length=100)
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    
    @Column(name="Address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="PhoneNum", length=20)
    public String getPhoneNum() {
        return this.phoneNum;
    }
    
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    
    @Column(name="Email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="DeptId", nullable=false)
    public int getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(int deptId) {
        this.deptId = deptId;
    }

    
    @Column(name="Gender", length=10)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="CardId", length=12)
    public String getCardId() {
        return this.cardId;
    }
    
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    
    @Column(name="Disable", nullable=false)
    public boolean isDisable() {
        return this.disable;
    }
    
    public void setDisable(boolean disable) {
        this.disable = disable;
    }

    
    @Column(name="Age")
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }

    
    @Column(name="Position", length=60)
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    
    @Column(name="Provice", length=60)
    public String getProvice() {
        return this.provice;
    }
    
    public void setProvice(String provice) {
        this.provice = provice;
    }

    
    @Column(name="Nationality", length=60)
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }




}


