package com.meals.backend.model;
// Generated Mar 20, 2018 2:44:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name="UserRole"
//    ,schema="dbo"
//    ,catalog="nsrp"
)
public class UserRole  implements java.io.Serializable {


     private int userRoleId;
     private String name;
     private String uid;
     private String code;
     private String description;
     private Date lastUpdated;
     private Date created;
     private String publicAccess;
     private boolean disable;

    public UserRole() {
    }

	
    public UserRole(int userRoleId, String name, boolean disable) {
        this.userRoleId = userRoleId;
        this.name = name;
        this.disable = disable;
    }
    public UserRole(int userRoleId, String name, String uid, String code, String description, Date lastUpdated, Date created, String publicAccess, boolean disable) {
       this.userRoleId = userRoleId;
       this.name = name;
       this.uid = uid;
       this.code = code;
       this.description = description;
       this.lastUpdated = lastUpdated;
       this.created = created;
       this.publicAccess = publicAccess;
       this.disable = disable;
    }
   
     @Id 

    
    @Column(name="UserRoleId", unique=true, nullable=false)
    public int getUserRoleId() {
        return this.userRoleId;
    }
    
    public void setUserRoleId(int userRoleId) {
        this.userRoleId = userRoleId;
    }

    
    @Column(name="Name", nullable=false, length=160)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="UID", length=11)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }

    
    @Column(name="Code", length=50)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="Description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LastUpdated", length=10)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Created", length=10)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="PublicAccess", length=8)
    public String getPublicAccess() {
        return this.publicAccess;
    }
    
    public void setPublicAccess(String publicAccess) {
        this.publicAccess = publicAccess;
    }

    
    @Column(name="Disable", nullable=false)
    public boolean isDisable() {
        return this.disable;
    }
    
    public void setDisable(boolean disable) {
        this.disable = disable;
    }




}


