package com.meals.backend.model;
// Generated Mar 20, 2018 2:44:46 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "Users"
	, schema = "dbo"
	, catalog = "nsrp"
	)
public class Users implements java.io.Serializable {

	private int userId;
	private int userRoleId;
	private String staffId;
	private boolean disable;
	private Date lastLogin;
	private String password;
	private Boolean selfRegistered;
	private String userName;

	public Users() {
	}

	public Users(int userId, int userRoleId, String staffId, boolean disable, String userName) {
		this.userId = userId;
		this.userRoleId = userRoleId;
		this.staffId = staffId;
		this.disable = disable;
		this.userName = userName;
	}

	public Users(int userId, int userRoleId, String staffId, boolean disable, Date lastLogin, String password,
			Boolean selfRegistered, String userName) {
		this.userId = userId;
		this.userRoleId = userRoleId;
		this.staffId = staffId;
		this.disable = disable;
		this.lastLogin = lastLogin;
		this.password = password;
		this.selfRegistered = selfRegistered;
		this.userName = userName;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "UserId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "UserRoleId", nullable = false)
	public int getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(int userRoleId) {
		this.userRoleId = userRoleId;
	}

	@Column(name = "StaffId", nullable = false, length = 12)
	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	@Column(name = "Disable", nullable = false)
	public boolean isDisable() {
		return this.disable;
	}

	public void setDisable(boolean disable) {
		this.disable = disable;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LastLogin", length = 10)
	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	@Column(name = "Password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "SelfRegistered")
	public Boolean getSelfRegistered() {
		return this.selfRegistered;
	}

	public void setSelfRegistered(Boolean selfRegistered) {
		this.selfRegistered = selfRegistered;
	}

	@Column(name = "UserName", nullable = false)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
